# Generated by Django 5.2.7 on 2025-11-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
