# Generated by Django 5.2.7 on 2025-11-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.IntegerField(default=1),
        ),
    ]
