# Generated by Django 5.2.7 on 2025-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_booking_num_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='pending_payment', max_length=20),
        ),
    ]
