# Generated by Django 5.2.7 on 2025-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_booking_is_paid_booking_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('jazzcash', 'JazzCash')], max_length=20, null=True),
        ),
    ]
