# Generated by Django 5.2.7 on 2025-12-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
    ]
